services:
  database:
    container_name: database
    image: postgres:16.0
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: workshop
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata:
