on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build the application
    runs-on: ubuntu-22.04
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Pin images
        uses: docker://ghcr.io/sethvargo/ratchet:0.4.0
        with:
          args: pin .github/workflows/main.yml
