on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build the application
    runs-on: ubuntu-22.04
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # ratchet:actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # ratchet:actions/setup-java@v3
        run: ./gradlew build --no-daemon
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
