on:
  push:
    branches:
      - main
jobs:
  build-backend:
    defaults:
      run:
        working-directory: backend
    name: Build the application
    runs-on: ubuntu-22.04
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # ratchet:actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # ratchet:actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build
      - uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # ratchet:docker/setup-buildx-action@v3
      - uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # ratchet:docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
