on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build the application
    runs-on: ubuntu-22.04
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # ratchet:actions/checkout@v4
